services:
  db:
    image: postgres:16.0
    env_file:
      - backend/.env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 1s
  app:
    build: .
    ports:
      - '8080:8080'
    env_file:
      - backend/.env
    depends_on:
      db:
        condition: service_healthy
